spring.application.name=statement-processor

# Server
server.port=${SERVER_PORT:8080}

# Spring profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# External API URLs
bank.api.base-url=${BANK_API_BASE_URL:http://localhost:3000}
summary.api.base-url=${MONTHLY_SUMMARY_API_BASE_URL:http://localhost:3000}


logging.structured.format.console=logstash
logging.structured.json.exclude=logger_name,thread_name,level,level_value,spanId,@version

# Actuator endpoints
management.endpoints.web.exposure.include=health,info

# Tracing: sample every request during development
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}


# OpenTelemetry resource attributes
management.opentelemetry.resource-attributes.service.name=bank-statment-service
management.opentelemetry.resource-attributes.deployment.environment=${APP_ENV:local}


# Monthly summary rate limit
resilience4j.ratelimiter.instances.monthlySummary.limitForPeriod=${SUMMARY_RATE_LIMIT:60}
resilience4j.ratelimiter.instances.monthlySummary.limitRefreshPeriod=${SUMMARY_RATE_REFRESH_PERIOD:1m}
resilience4j.ratelimiter.instances.monthlySummary.timeoutDuration=${SUMMARY_RATE_TIMEOUT:0}