spring.application.name=statement-processor

bank.api.base-url=http://localhost:3000

summary.api.base-url=http://localhost:3000


logging.structured.format.console=logstash
logging.structured.json.exclude=logger_name,thread_name,level,level_value,spanId,@version
# Actuator endpoints
management.endpoints.web.exposure.include=health,info

# Tracing: sample every request during development
management.tracing.sampling.probability=1.0


# OpenTelemetry resource attributes
management.opentelemetry.resource-attributes.service.name=bank-statment-service
management.opentelemetry.resource-attributes.deployment.environment=${APP_ENV:local}

